### ISSUE TITLE
npm @backstage/cli create-app fails

### ISSUE THREAD

**Issue by hooloovooo** [spotify/backstage#1700]
Hi! Backstage-cli create-app fails with the following error message.

$ backstage-cli plugin:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:

Error: Cannot find module 'esbuild'
Require stack:
- ~/projects/hello-world/node_modules/rollup-plugin-esbuild/dist/index.js
- ~/projects/hello-world/node_modules/@backstage/cli/dist/cjs/build-022aa68a.js
- ~/projects/hello-world/node_modules/@backstage/cli/dist/cjs/index-8177d57e.js
- ~/projects/hello-world/node_modules/@backstage/cli/dist/index.cjs.js
- ~/projects/hello-world/node_modules/@backstage/cli/bin/backstage-cli

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'plugin-welcome'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by shmidt-i** [comment]
Verified, works in 0.1.1-alpha.15
